{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "d97e8868_1cb1aaba",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 14,
      "author": {
        "id": 1000341
      },
      "writtenOn": "2022-11-30T15:10:55Z",
      "side": 1,
      "message": "Does it mean that even with these errors the SWd is still usable?",
      "range": {
        "startLine": 14,
        "startChar": 7,
        "endLine": 14,
        "endChar": 59
      },
      "revId": "075a26b6c93695d6ee0037be515c375af59f5fb5",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}