{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "d851cb93_4f29faa5",
        "filename": "bl31/aarch64/runtime_exceptions.S",
        "patchSetId": 18
      },
      "lineNbr": 320,
      "author": {
        "id": 1000883
      },
      "writtenOn": "2023-05-30T09:13:46Z",
      "side": 0,
      "message": "nit: might be good to leave a little note saying that it isn\u0027t properly handled because it\u0027s expected to panic",
      "revId": "16cb3be875f07d3eb09fe206778a85be0c4ee802",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "30778942_6ef984af",
        "filename": "bl31/aarch64/runtime_exceptions.S",
        "patchSetId": 18
      },
      "lineNbr": 320,
      "author": {
        "id": 1000102
      },
      "writtenOn": "2023-10-06T14:39:27Z",
      "side": 0,
      "message": "Acknowledged",
      "parentUuid": "d851cb93_4f29faa5",
      "revId": "16cb3be875f07d3eb09fe206778a85be0c4ee802",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}