{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "858a16f2_49204600",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 29,
      "author": {
        "id": 1000114
      },
      "writtenOn": "2021-06-16T00:05:50Z",
      "side": 1,
      "message": "is this true though? why is ehf_entering_normal_world not being called the second time around?",
      "range": {
        "startLine": 28,
        "startChar": 0,
        "endLine": 29,
        "endChar": 48
      },
      "revId": "22007a54fb28732cf60eae7e363bc026a1d85b7b",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}