{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a4426729_b0b52616",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 43
      },
      "lineNbr": 0,
      "author": {
        "id": 1000206
      },
      "writtenOn": "2021-10-14T11:21:45Z",
      "side": 1,
      "message": "Several test failures occurring here that are not reproducible locally. Running the legacy CI to cross-check. ",
      "revId": "4caa4943c5597e283286aaa298064387c3e60bb8",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "96d6a6ca_6c3189a9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 43
      },
      "lineNbr": 0,
      "author": {
        "id": 1000206
      },
      "writtenOn": "2021-10-14T14:28:38Z",
      "side": 1,
      "message": "No overlap between test failures from the OpenCI and the internal CI - looks like CI instability.",
      "revId": "4caa4943c5597e283286aaa298064387c3e60bb8",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}