{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "5bd1aca0_a0bc17a1",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 1000493
      },
      "writtenOn": "2021-09-24T04:01:54Z",
      "side": 1,
      "message": "Hi, @Madhukar and @Joanna,\n\nIt seems that CI failure isn\u0027t caused by my patch, please help on it, thanks.\n\nJiafei.",
      "revId": "52a1e9ff37251987b71b743951038cd8d1fa0ba4",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}