{
  "comments": [
    {
      "key": {
        "uuid": "fe96f097_0a05a9f7",
        "filename": "drivers/auth/auth_mod.c",
        "patchSetId": 5
      },
      "lineNbr": 14,
      "author": {
        "id": 1000328
      },
      "writtenOn": "2020-12-16T06:19:21Z",
      "side": 1,
      "message": "Please move this inclusion after line no.16",
      "range": {
        "startLine": 14,
        "startChar": 0,
        "endLine": 14,
        "endChar": 34
      },
      "revId": "69b114d273b1e549f123fe8edd0b28066ac3fe66",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "43c7382c_4e2cc86d",
        "filename": "drivers/auth/auth_mod.c",
        "patchSetId": 5
      },
      "lineNbr": 15,
      "author": {
        "id": 1000328
      },
      "writtenOn": "2020-12-16T06:19:21Z",
      "side": 1,
      "message": "Why we need to include this file again which is already included in \u0027auth_mod.h\u0027",
      "range": {
        "startLine": 15,
        "startChar": 0,
        "endLine": 15,
        "endChar": 32
      },
      "revId": "69b114d273b1e549f123fe8edd0b28066ac3fe66",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": true
    }
  ]
}