{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b64bb616_53faf6e0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000263
      },
      "writtenOn": "2021-12-02T10:12:49Z",
      "side": 1,
      "message": "CI failures are not related to this patch.",
      "revId": "78d7e819798ace643b6e22025dc76aedb199bbd5",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "da2c3840_1045a894",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000102
      },
      "writtenOn": "2021-12-02T17:43:29Z",
      "side": 1,
      "message": "@Please provide CoR",
      "revId": "78d7e819798ace643b6e22025dc76aedb199bbd5",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}