{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1e11cb5e_85594e6a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000206
      },
      "writtenOn": "2023-04-19T10:28:37Z",
      "side": 1,
      "message": "CI failure unrelated (network issue in one of the builds).",
      "revId": "9a905a7d86867bab8a5d9befd40a67a6ab9aaea2",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}