{
  "comments": [
    {
      "key": {
        "uuid": "045a2f3d_26da20fc",
        "filename": "plat/nvidia/tegra/soc/t194/drivers/se/se_private.h",
        "patchSetId": 2
      },
      "lineNbr": 77,
      "author": {
        "id": 1000098
      },
      "writtenOn": "2020-01-30T23:01:06Z",
      "side": 1,
      "message": "In file plat/nvidia/tegra/soc/t194/drivers/se/se.c, lines 194-197, similar fix might be needed.",
      "revId": "f30514216776148cd1f64d9a668e21d1adaedc06",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": true
    }
  ]
}